[package]
name = "libzcashlc"
version = "0.8.1"
authors = [
    "Jack Grigg <jack@electriccoin.co>",
    "Francisco Gindre",
    "Lukas Korba <lukas@tangiblecodes.com>",
]
license = "MIT"
edition = "2021"
rust-version = "1.60"
build = "build.rs"

[dependencies]
hex = "0.4"
memuse = "0.2.1"
orchard = "0.8"
prost = "0.12"
rusqlite = "0.29"
sapling = { package = "sapling-crypto", version = "0.1", default-features = false }
schemer = "0.2.1"
secp256k1 = "0.26"
secrecy = "0.8"
zcash_address = { version = "0.3" }
zcash_client_backend = { version = "0.12", features = ["orchard", "transparent-inputs", "unstable"] }
zcash_client_sqlite = { version = "0.10.1", features = ["orchard", "transparent-inputs", "unstable"] }
zcash_primitives = "0.15"
zcash_proofs = "0.15"

# FFI
anyhow = "1.0"
ffi_helpers = "0.3"

# Initialization
cfg-if = "1.0"
rayon = "1.7"

# Logging
log-panics = "2.0"
once_cell = "1.0"
sharded-slab = "0.1"
tracing = "0.1"
tracing-subscriber = "0.3"

[build-dependencies]
bindgen = "0.69"
cbindgen = "0.26"
cc = "1.0"

[lib]
name = "zcashlc"
path = "src/lib.rs"
crate-type = ["staticlib"]

[profile.release]
lto = true

[patch.crates-io]
incrementalmerkletree = { git = "https://github.com/zcash/incrementalmerkletree", rev = "337f59179eda51261e9ddfc6b18e8fb84ea277c9" }
shardtree = { git = "https://github.com/zcash/incrementalmerkletree", rev = "337f59179eda51261e9ddfc6b18e8fb84ea277c9" }
zcash_address = { git = "https://github.com/zcash/librustzcash.git", rev = "34cf6d286a201caf7dfee29fbee867d547afc486" }
zcash_client_backend = { git = "https://github.com/zcash/librustzcash.git", rev = "34cf6d286a201caf7dfee29fbee867d547afc486" }
zcash_client_sqlite = { git = "https://github.com/zcash/librustzcash.git", rev = "34cf6d286a201caf7dfee29fbee867d547afc486" }
zcash_encoding = { git = "https://github.com/zcash/librustzcash.git", rev = "34cf6d286a201caf7dfee29fbee867d547afc486" }
zcash_primitives = { git = "https://github.com/zcash/librustzcash.git", rev = "34cf6d286a201caf7dfee29fbee867d547afc486" }
zcash_proofs = { git = "https://github.com/zcash/librustzcash.git", rev = "34cf6d286a201caf7dfee29fbee867d547afc486" }
zcash_protocol = { git = "https://github.com/zcash/librustzcash.git", rev = "34cf6d286a201caf7dfee29fbee867d547afc486" }
