[package]
name = "libzcashlc"
version = "0.1.0"
authors = ["Jack Grigg <jack@z.cash>",
            "Francisco Gindre <francisco@z.cash>",
]
edition = "2018"
build = "build.rs"

[dependencies]
failure = "0.1"
ffi_helpers = "0.2"
hex = "0.4"
zcash_client_backend = { version = "0.5", features = ["transparent-inputs"] }
zcash_client_sqlite = { version = "0.3", features = ["transparent-inputs"] }
zcash_primitives = "0.5"
zcash_proofs = "0.5"
orchard = "=0.1.0-beta.3"
#### Temporary additions: ####################################
base58 = "0.1.0"
sha2 = "0.9"
hdwallet = "0.3.0"
ripemd160 = "0.9"
secp256k1 = "0.20"
time = "0.2"
num-bigint = "0.3.3"
##############################################################

[build-dependencies]
cbindgen = "0.14"

[lib]
name = "zcashlc"
path = "src/lib.rs"
crate-type = ["staticlib"]

[profile.release]
lto = true

[patch.crates-io]
#zcash_address = { git = "https://github.com/zcash/librustzcash.git", rev = "33f6ffedcfd7665e4a709e7593b9fddea64a2952" }
zcash_client_sqlite = { git = "https://github.com/zcash/librustzcash.git", rev = "33f6ffedcfd7665e4a709e7593b9fddea64a2952" }
zcash_client_backend = { git = "https://github.com/zcash/librustzcash.git", rev = "33f6ffedcfd7665e4a709e7593b9fddea64a2952" }
zcash_primitives = { git = "https://github.com/zcash/librustzcash.git", rev = "33f6ffedcfd7665e4a709e7593b9fddea64a2952" }
zcash_proofs = { git = "https://github.com/zcash/librustzcash.git", rev = "33f6ffedcfd7665e4a709e7593b9fddea64a2952" }
hdwallet = { git = "https://github.com/nuttycom/hdwallet", rev = "9b4c1bdbe0517e3a7a8f285d6048a37d472ba3bc" }

[features]
mainnet = ["zcash_client_sqlite/mainnet"]
testnet = []
