[package]
name = "libzcashlc"
version = "0.1.0"
authors = [
    "Jack Grigg <jack@z.cash>",
    "Francisco Gindre <francisco@z.cash>",
]
license = "MIT"
edition = "2018"
build = "build.rs"

[dependencies]
failure = "0.1"
ffi_helpers = "0.2"
hex = "0.4"
memuse = "0.2.1"
schemer = "0.2.1"
secp256k1 = "0.21"
secrecy = "0.8"

zcash_address = { version = "0.2" }
zcash_client_backend = { version = "0.6.1", features = ["transparent-inputs", "unstable"] }
zcash_client_sqlite = { version = "0.4.2", features = ["transparent-inputs", "unstable"] }
zcash_primitives = "0.9.1"
zcash_proofs = "0.9"

[build-dependencies]
cbindgen = "0.14"

[lib]
name = "zcashlc"
path = "src/lib.rs"
crate-type = ["staticlib"]

[profile.release]
lto = true

[features]
mainnet = ["zcash_client_sqlite/mainnet"]
testnet = []

[patch.crates-io]

zcash_client_backend = { git = "https://github.com/zcash/librustzcash.git", rev = "7cbb2778843832e53b26470d95d28a4e73c93205" }
zcash_client_sqlite = { git = "https://github.com/zcash/librustzcash.git", rev = "7cbb2778843832e53b26470d95d28a4e73c93205" }
zcash_primitives = { git = "https://github.com/zcash/librustzcash.git", rev = "7cbb2778843832e53b26470d95d28a4e73c93205" }
zcash_proofs = { git = "https://github.com/zcash/librustzcash.git", rev = "7cbb2778843832e53b26470d95d28a4e73c93205" }
zcash_address = { git = "https://github.com/zcash/librustzcash.git", rev = "7cbb2778843832e53b26470d95d28a4e73c93205" }