[package]
name = "libzcashlc"
version = "0.4.0-rc.2"
authors = [
    "Jack Grigg <jack@z.cash>",
    "Francisco Gindre <francisco@z.cash>",
]
license = "MIT"
edition = "2021"
rust-version = "1.60"
build = "build.rs"

[dependencies]
hex = "0.4"
memuse = "0.2.1"
prost = "0.12"
rusqlite = "0.29"
schemer = "0.2.1"
secp256k1 = "0.26"
secrecy = "0.8"
orchard = { version = "0.6", default-features = false }
zcash_address = { version = "0.3" }
zcash_client_backend = { version = "=0.10.0-rc.3", features = ["transparent-inputs", "unstable"] }
zcash_client_sqlite = { version = "=0.8.0-rc.4", features = ["transparent-inputs", "unstable"] }
zcash_primitives = "=0.13.0-rc.1"
zcash_proofs = "=0.13.0-rc.1"

# FFI
anyhow = "1.0"
ffi_helpers = "0.3"

# Initialization
cfg-if = "1.0"
rayon = "1.7"

# Logging
log-panics = "2.0"
once_cell = "1.0"
sharded-slab = "0.1"
tracing = "0.1"
tracing-subscriber = "0.3"

[build-dependencies]
bindgen = "0.68"
cbindgen = "0.25"
cc = "1.0"

[lib]
name = "zcashlc"
path = "src/lib.rs"
crate-type = ["staticlib"]

[profile.release]
lto = true

[features]
mainnet = ["zcash_client_sqlite/mainnet"]
testnet = []
