[package]
name = "libzcashlc"
version = "0.3.1"
authors = [
    "Jack Grigg <jack@z.cash>",
    "Francisco Gindre <francisco@z.cash>",
]
license = "MIT"
edition = "2021"
rust-version = "1.60"
build = "build.rs"

[dependencies]
hex = "0.4"
memuse = "0.2.1"
schemer = "0.2.1"
secp256k1 = "0.21"
secrecy = "0.8"
orchard = { version = "0.4", default-features = false }
zcash_address = { version = "0.2" }
zcash_client_backend = { version = "0.9.0", features = ["transparent-inputs", "unstable"] }
zcash_client_sqlite = { version = "0.7.0", features = ["transparent-inputs", "unstable"] }
zcash_primitives = "0.11.0"
zcash_proofs = "0.11.0"

# FFI
anyhow = "1.0"
ffi_helpers = "0.3"

[build-dependencies]
cbindgen = "0.24"

[lib]
name = "zcashlc"
path = "src/lib.rs"
crate-type = ["staticlib"]

[profile.release]
lto = true

[features]

mainnet = ["zcash_client_sqlite/mainnet"]
testnet = []
