[package]
name = "libzcashlc"
version = "0.0.8"
authors = ["Jack Grigg <jack@z.cash>",
            "Francisco Gindre <francisco@z.cash>",
]
edition = "2018"
build = "build.rs"

[dependencies]
failure = "0.1"
ffi_helpers = "0.2"
hex = "0.4"
zcash_client_backend = "0.5"
zcash_client_sqlite = "0.3"
zcash_primitives = "0.5"
zcash_proofs = "0.5"

#### Temporary additions: ####################################
#bitvec = "0.22"
base58 = "0.1.0"
#sha2 = "0.9"
#bs58 = { version = "0.3", features = ["check"] }
hdwallet = "=0.3.0"
#ripemd160 = "0.9"
secp256k1 = "0.19"
time = "0.2"
num-bigint = "0.3.3"
##############################################################

#[dependencies.zcash_proofs]
#version = "0.5"
#default-features = false
#features = ["local-prover"]

[build-dependencies]
cbindgen = "0.14"

[lib]
name = "zcashlc"
path = "src/lib.rs"
crate-type = ["staticlib"]

[profile.release]
lto = true

# Revision corresponds to the partially-complete auto-shielding version, with the NU5
# consensus branch ID and activation heights backported onto it.
# https://github.com/zcash/librustzcash/pull/555
[patch.crates-io]
zcash_client_backend = { git = 'https://github.com/zcash/librustzcash.git', rev='098dcc2ae02841e6a2b17bbb6253de970b1ff41c' }
zcash_client_sqlite = { git = 'https://github.com/zcash/librustzcash.git', rev='098dcc2ae02841e6a2b17bbb6253de970b1ff41c' }
zcash_primitives = { git = 'https://github.com/zcash/librustzcash.git', rev='098dcc2ae02841e6a2b17bbb6253de970b1ff41c' }
zcash_proofs = { git = 'https://github.com/zcash/librustzcash.git', rev='098dcc2ae02841e6a2b17bbb6253de970b1ff41c' }

[features]
mainnet = ["zcash_client_sqlite/mainnet"]
testnet = []
