[package]
name = "libzcashlc"
version = "0.1.0"
authors = ["Jack Grigg <jack@z.cash>",
            "Francisco Gindre <francisco@z.cash>",
]
edition = "2018"
build = "build.rs"

[dependencies]
failure = "0.1"
ffi_helpers = "0.2"
hex = "0.4"
memuse = "0.2.1"
schemer = "0.2"
secp256k1 = "0.21"
secrecy = "0.8"

zcash_address = { version = "0.1" }
zcash_client_backend = { version = "0.5", features = ["transparent-inputs", "unstable"] }
zcash_client_sqlite = { version = "0.3", features = ["transparent-inputs", "unstable"] }
zcash_primitives = "0.7"
zcash_proofs = "0.7"

[build-dependencies]
cbindgen = "0.14"

[lib]
name = "zcashlc"
path = "src/lib.rs"
crate-type = ["staticlib"]

[profile.release]
lto = true

# Revision corresponds to zcash_primitives 0.6.0 plus the NU5 mainnet activation height.
# We also need zcash_client_backend and zcash_client_sqlite, which haven't been published
# with NU5 updates yet.
[patch.crates-io]
zcash_address = { git = 'https://github.com/zcash/librustzcash.git', rev='4e631697c4d9bb55c66c4730c1c7479d9cd71706' }
zcash_client_backend = { git = 'https://github.com/zcash/librustzcash.git', rev='4e631697c4d9bb55c66c4730c1c7479d9cd71706' }
zcash_client_sqlite = { git = 'https://github.com/zcash/librustzcash.git', rev='4e631697c4d9bb55c66c4730c1c7479d9cd71706' }
zcash_primitives = { git = 'https://github.com/zcash/librustzcash.git', rev='4e631697c4d9bb55c66c4730c1c7479d9cd71706' }
zcash_proofs = { git = 'https://github.com/zcash/librustzcash.git', rev='4e631697c4d9bb55c66c4730c1c7479d9cd71706' }
group = { git = "https://github.com/zkcrypto/group.git", rev = "f61e3e420ed1220c8f1f80988f8c6c5e202d8715" }

[features]
mainnet = ["zcash_client_sqlite/mainnet"]
testnet = []
