[package]
name = "libzcashlc"
version = "0.1.0"
authors = ["Jack Grigg <jack@z.cash>",
            "Francisco Gindre <francisco@z.cash>",
]
edition = "2018"
build = "build.rs"

[dependencies]
failure = "0.1"
ffi_helpers = "0.2"
hex = "0.4"
memuse = "0.2.1"
schemer = "0.2"
secp256k1 = "0.21"
secrecy = "0.8"

zcash_address = { version = "0.1" }
zcash_client_backend = { version = "0.5", features = ["transparent-inputs", "unstable"] }
zcash_client_sqlite = { version = "0.3", features = ["transparent-inputs", "unstable"] }
zcash_primitives = "0.7"
zcash_proofs = "0.7"

[build-dependencies]
cbindgen = "0.14"

[lib]
name = "zcashlc"
path = "src/lib.rs"
crate-type = ["staticlib"]

[profile.release]
lto = true

# Revision corresponds to zcash_primitives 0.6.0 plus the NU5 mainnet activation height.
# We also need zcash_client_backend and zcash_client_sqlite, which haven't been published
# with NU5 updates yet.
[patch.crates-io]
zcash_address = { git = 'https://github.com/zcash/librustzcash.git', rev='022964056fbe6dac8fe3adbf89f29c046cdc4cec' }
zcash_client_backend = { git = 'https://github.com/zcash/librustzcash.git', rev='022964056fbe6dac8fe3adbf89f29c046cdc4cec' }
zcash_client_sqlite = { git = 'https://github.com/zcash/librustzcash.git', rev='022964056fbe6dac8fe3adbf89f29c046cdc4cec' }
zcash_primitives = { git = 'https://github.com/zcash/librustzcash.git', rev='022964056fbe6dac8fe3adbf89f29c046cdc4cec' }
zcash_proofs = { git = 'https://github.com/zcash/librustzcash.git', rev='022964056fbe6dac8fe3adbf89f29c046cdc4cec' }
schemer = { git = "https://github.com/aschampion/schemer.git", rev = "6726b60f43f72c6e24a18d31be0ec7d42829e5e1" }
schemer-rusqlite = { git = "https://github.com/aschampion/schemer.git", rev = "6726b60f43f72c6e24a18d31be0ec7d42829e5e1" }

[features]
mainnet = ["zcash_client_sqlite/mainnet"]
testnet = []
