[package]
name = "libzcashlc"
version = "0.11.0"
authors = [
    "Jack Grigg <jack@electriccoin.co>",
    "Francisco Gindre",
    "Lukas Korba <lukas@tangiblecodes.com>",
]
license = "MIT"
edition = "2021"
rust-version = "1.80"
build = "build.rs"

[dependencies]

# Zcash
orchard = "0.10"
sapling = { package = "sapling-crypto", version = "0.3", default-features = false }
zcash_address = { version = "0.6" }
zcash_client_backend = { version = "0.15", features = ["orchard", "tor", "transparent-inputs", "unstable", "pczt"] }
zcash_client_sqlite = { version = "0.13", features = ["orchard", "transparent-inputs", "unstable", "serde"] }
zcash_note_encryption = "0.4.1"
zcash_primitives = "0.20"
zcash_proofs = "0.20"
zcash_protocol = "0.4"
zip32 = "0.1.2"
pczt = { version = "0.0.0", features = ["prover"] }

# Infrastructure
prost = "0.13"
rusqlite = "0.32"
secrecy = "0.8"

# FFI
anyhow = "1.0"
ffi_helpers = "0.3"
uuid = "1.1"

# Initialization
cfg-if = "1.0"
rayon = "1.7"

# Logging
log-panics = "2.0"
once_cell = "1.0"
sharded-slab = "0.1"
tracing = "0.1"
tracing-subscriber = "0.3"

# Tor
tor-rtcompat = "0.23"
rust_decimal = { version = "1", default-features = false, features = ["c-repr"] }
# - The "static" feature is required for the "compression" default feature of arti-client.
xz2 = { version = "0.1", features = ["static"] }

[build-dependencies]
bindgen = "0.70"
cbindgen = "0.27"
cc = "1.0"

[lib]
name = "zcashlc"
path = "src/lib.rs"
crate-type = ["staticlib"]

[profile.release]
lto = true

[patch.crates-io]
zcash_address = { git = "https://github.com/zcash/librustzcash.git", rev = "67fe5f8c8851b17c4129c9f3a590dde00d59f667" }
zcash_client_backend = { git = "https://github.com/zcash/librustzcash.git", rev = "67fe5f8c8851b17c4129c9f3a590dde00d59f667" }
zcash_client_sqlite = { git = "https://github.com/zcash/librustzcash.git", rev = "67fe5f8c8851b17c4129c9f3a590dde00d59f667" }
zcash_encoding = { git = "https://github.com/zcash/librustzcash.git", rev = "67fe5f8c8851b17c4129c9f3a590dde00d59f667" }
zcash_primitives = { git = "https://github.com/zcash/librustzcash.git", rev = "67fe5f8c8851b17c4129c9f3a590dde00d59f667" }
zcash_proofs = { git = "https://github.com/zcash/librustzcash.git", rev = "67fe5f8c8851b17c4129c9f3a590dde00d59f667" }
zcash_protocol = { git = "https://github.com/zcash/librustzcash.git", rev = "67fe5f8c8851b17c4129c9f3a590dde00d59f667" }
pczt = { git = "https://github.com/zcash/librustzcash.git", rev = "67fe5f8c8851b17c4129c9f3a590dde00d59f667" }
orchard = { git = "https://github.com/zcash/orchard.git", rev = "bcd08e1d23e70c42a338f3e3f79d6f4c0c219805" }
sapling-crypto = { git = "https://github.com/zcash/sapling-crypto.git", rev = "29cff9683cdf2f0c522ff3224081dfb4fbc80248" }
