name: Binary preview

on:
  push:
    branches:
      - 'feature/**'
      - 'release/**'
      - 'hotfix/**'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: macos-13
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Create, or merge into, the corresponding preview branch
        run: git switch -c 'preview/${GITHUB_REF_NAME}' || git switch -m 'preview/${GITHUB_REF_NAME}'

      # https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md#xcode
      - name: Select the required Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_14.3.1.app/Contents/Developer'

      - name: Install the required Rust targets
        run: make install

      - name: Configure sccache
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.7

      - name: Build the binaries
        run: make xcframework
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'make xcframework'
          branch: 'preview/${{ github.ref_name }}'
          create_branch: true
